name: Release

on:
  push:
    branches:
      - main

jobs:
  Linux:
    name: Publish build on GitHub releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Build
        run: |
          cd build
          cmake ..
          make

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            files: |
                build/bundle
