name: Release

on:
  push:
    branches:
      - main

jobs:
  Linux:
    name: Publish build on GitHub releases
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Build
        run: |
          cd build
          cmake ..
          make

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.date.outputs.date }}"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/bundle"
          tag: "${{ steps.date.outputs.date }}"
